version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 10s
  pizza-adminer:
    container_name: pizza-adminer
    image: adminer
    restart: always
    env_file:
      - .env
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
  pizza-server:
    container_name: pizza-server
    build: "."
    restart: always
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./:/pizza-server